[package]
name = "component_replicated_derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.42" }
syn = { version = "2.0.110", features = ["full"] }
proc-macro2 = { version = "1.0.103" }

